<?php
return array (
  17 => 
  array (
    'id' => '17',
    'catid' => '6',
    'typeid' => '0',
    'title' => '强攻360腹地：百度杀毒正式亮相',
    'style' => '',
    'thumb' => '/2013/0418/20130418030133817.jpg',
    'keywords' => '强攻 腹地 百度',
    'description' => '早在2月份百度面向泰国推出百度杀毒软件2013的时候，我们就预言，百度很快就会面向国内市场推出杀毒软件，这一天来的很快。今天，百度杀毒（Baidu Antivirus）正式亮相，官网提供了百度杀毒.',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=17',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1366268368',
    'updatetime' => '1366965210',
    'hitsid' => 'c-1-17',
    'views' => '56',
    'yesterdayviews' => '19',
    'dayviews' => '2',
    'weekviews' => '4',
    'monthviews' => '56',
  ),
  107 => 
  array (
    'id' => '107',
    'catid' => '6',
    'typeid' => '0',
    'title' => '传黑石放弃竞购戴尔 具体原因不明',
    'style' => '',
    'thumb' => '',
    'keywords' => '黑石 放弃 竞购 戴尔 具体',
    'description' => '
传黑石放弃竞购戴尔 具体原因不明

        teikaei 发布于 2013-04-19 10:53:41| 次阅读  稿源:网易科技报道      ...',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=107',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '0',
    'islink' => '0',
    'username' => 'caijixia',
    'inputtime' => '1366364775',
    'updatetime' => '1366489213',
    'hitsid' => 'c-1-107',
    'views' => '13',
    'yesterdayviews' => '11',
    'dayviews' => '1',
    'weekviews' => '13',
    'monthviews' => '13',
  ),
  28 => 
  array (
    'id' => '28',
    'catid' => '6',
    'typeid' => '0',
    'title' => '[图]一天一美元：Google推出OneToday慈善应用',
    'style' => '',
    'thumb' => '',
    'keywords' => '一天 美元 Google 推出 OneToday',
    'description' => '
        
在规模有限的试点期结束后，我猜Google会向所有人开放该应用的。但具体是什么时候，Google还没说。除了Android，该应用...',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=28',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '0',
    'islink' => '0',
    'username' => 'caijixia',
    'inputtime' => '1366362444',
    'updatetime' => '1366430492',
    'hitsid' => 'c-1-28',
    'views' => '4',
    'yesterdayviews' => '3',
    'dayviews' => '1',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  113 => 
  array (
    'id' => '113',
    'catid' => '6',
    'typeid' => '0',
    'title' => '四成五的比特币交易平台以倒闭告终',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2013/0428/20130428071010631.jpg',
    'keywords' => '四成 比特 交易平台',
    'description' => '一项研究发现（PDF），四成五的比特币交易平台以 关闭/倒闭而告终。计算机科学家 Tyler Moore和 Nicolas Christin发现有40个交易平台...',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=113',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1367147371',
    'updatetime' => '1367147530',
    'hitsid' => 'c-1-113',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '6',
    'typeid' => '0',
    'title' => '科技界十位大佬说过的最愚蠢的话',
    'style' => '',
    'thumb' => '/2013/0418/20130418021032792.jpg',
    'keywords' => '科技界 十位 说过',
    'description' => '科技博客Business Insider日前总结了科技行业十位最聪明的人曾经做出的最离谱预测.',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1366265240',
    'updatetime' => '1367735062',
    'hitsid' => 'c-1-2',
    'views' => '10',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '6',
    'typeid' => '0',
    'title' => '[视频]喜欢哪个？诺基亚Lumia WP8家族屏幕对比',
    'style' => '',
    'thumb' => '',
    'keywords' => '视频 喜欢 哪个',
    'description' => '随着Lumia 520、720在全球不少地区开卖，诺基亚WP8产品线已经布局完成。诺基亚的WP8 Lumia家族五个成员——920、820、720、620、520，涵盖了高、中、低三档。在相似的外观下，这五款Lumia究竟差多少',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1366268119',
    'updatetime' => '1366364681',
    'hitsid' => 'c-1-5',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  16 => 
  array (
    'id' => '16',
    'catid' => '6',
    'typeid' => '0',
    'title' => '强攻360腹地：百度杀毒正式亮相',
    'style' => '',
    'thumb' => '/2013/0418/20130418030133338.jpg',
    'keywords' => '强攻 腹地 百度',
    'description' => '早在2月份百度面向泰国推出百度杀毒软件2013的时候，我们就预言，百度很快就会面向国内市场推出杀毒软件，这一天来的很快。今天，百度杀毒（Baidu Antivirus）正式亮相，官网提供了百度杀毒.',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=16',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1366268368',
    'updatetime' => '1366268926',
    'hitsid' => 'c-1-16',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  114 => 
  array (
    'id' => '114',
    'catid' => '6',
    'typeid' => '0',
    'title' => '消息称iOS 7将继续攻占车载系统 增加地图和Siri存在性',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2013/0501/20130501015933332.jpg',
    'keywords' => '消息称 继续 攻占',
    'description' => '    昨天，有知情人士爆料称iOS7将拥有全新的界面设计，新界面看起来非常扁平。今天，最新的消息显示苹果想要在下一代移动操作系统中继...',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=114',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1367344714',
    'updatetime' => '1367344780',
    'hitsid' => 'c-1-114',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  111 => 
  array (
    'id' => '111',
    'catid' => '6',
    'typeid' => '0',
    'title' => '微软将对旗下产品品牌再次重新设计？设计图曝光',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2013/0428/20130428070314109.jpg',
    'keywords' => '微软 将对 旗下',
    'description' => '最近几年微软逐步的开始重塑企业形象，尤其是为旗下的产品LOGO进行了重新包装升级。从Office到Visual Studio，从Hotmail（新Outlook.com）...',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=111',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1367146875',
    'updatetime' => '1367147017',
    'hitsid' => 'c-1-111',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  110 => 
  array (
    'id' => '110',
    'catid' => '6',
    'typeid' => '0',
    'title' => '腾讯视频将引进几乎全部高收视率英剧',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2013/0427/20130427083429100.jpg',
    'keywords' => '腾讯 视频 引进',
    'description' => '腾讯视频首批引进的英剧包括英国6大制片公司和电视台的13部近500集英剧，包括《神秘博士》《飞天大盗》《梅林传奇》《黑镜》《疯城记》《欢喜冤家》《皮囊》《IT狂人》《远古入侵》等。',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=110',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1367065936',
    'updatetime' => '1367066087',
    'hitsid' => 'c-1-110',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>