<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '7',
    'typeid' => '0',
    'title' => '科技界十位大佬说过的最愚蠢的话',
    'style' => '',
    'thumb' => '/2013/0418/20130418021032792.jpg',
    'keywords' => '科技界 十位 说过',
    'description' => '科技博客Business Insider日前总结了科技行业十位最聪明的人曾经做出的最离谱预测.',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '1',
    'username' => 'phpcms',
    'inputtime' => '1366265240',
    'updatetime' => '1366265432',
    'systems' => 'Win2000/WinXP/Win2003',
    'copytype' => '',
    'language' => '',
    'classtype' => '',
    'version' => '',
    'filesize' => 'Unkown',
    'stars' => '',
    'hitsid' => 'c-2-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>