<?php
return array (
  17 => 
  array (
    'id' => '17',
    'catid' => '6',
    'typeid' => '0',
    'title' => '强攻360腹地：百度杀毒正式亮相',
    'style' => '',
    'thumb' => '/2013/0418/20130418030133817.jpg',
    'keywords' => '强攻 腹地 百度',
    'description' => '早在2月份百度面向泰国推出百度杀毒软件2013的时候，我们就预言，百度很快就会面向国内市场推出杀毒软件，这一天来的很快。今天，百度杀毒（Baidu Antivirus）正式亮相，官网提供了百度杀毒.',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=17',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1366268368',
    'updatetime' => '1366965210',
    'hitsid' => 'c-1-17',
    'views' => '56',
    'yesterdayviews' => '19',
    'dayviews' => '2',
    'weekviews' => '4',
    'monthviews' => '56',
  ),
  107 => 
  array (
    'id' => '107',
    'catid' => '6',
    'typeid' => '0',
    'title' => '传黑石放弃竞购戴尔 具体原因不明',
    'style' => '',
    'thumb' => '',
    'keywords' => '黑石 放弃 竞购 戴尔 具体',
    'description' => '
传黑石放弃竞购戴尔 具体原因不明

        teikaei 发布于 2013-04-19 10:53:41| 次阅读  稿源:网易科技报道      ...',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=107',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '0',
    'islink' => '0',
    'username' => 'caijixia',
    'inputtime' => '1366364775',
    'updatetime' => '1366489213',
    'hitsid' => 'c-1-107',
    'views' => '13',
    'yesterdayviews' => '11',
    'dayviews' => '1',
    'weekviews' => '13',
    'monthviews' => '13',
  ),
  28 => 
  array (
    'id' => '28',
    'catid' => '6',
    'typeid' => '0',
    'title' => '[图]一天一美元：Google推出OneToday慈善应用',
    'style' => '',
    'thumb' => '',
    'keywords' => '一天 美元 Google 推出 OneToday',
    'description' => '
        
在规模有限的试点期结束后，我猜Google会向所有人开放该应用的。但具体是什么时候，Google还没说。除了Android，该应用...',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=28',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '0',
    'islink' => '0',
    'username' => 'caijixia',
    'inputtime' => '1366362444',
    'updatetime' => '1366430492',
    'hitsid' => 'c-1-28',
    'views' => '4',
    'yesterdayviews' => '3',
    'dayviews' => '1',
    'weekviews' => '4',
    'monthviews' => '4',
  ),
  113 => 
  array (
    'id' => '113',
    'catid' => '6',
    'typeid' => '0',
    'title' => '四成五的比特币交易平台以倒闭告终',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2013/0428/20130428071010631.jpg',
    'keywords' => '四成 比特 交易平台',
    'description' => '一项研究发现（PDF），四成五的比特币交易平台以 关闭/倒闭而告终。计算机科学家 Tyler Moore和 Nicolas Christin发现有40个交易平台...',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=113',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1367147371',
    'updatetime' => '1367147530',
    'hitsid' => 'c-1-113',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  114 => 
  array (
    'id' => '114',
    'catid' => '6',
    'typeid' => '0',
    'title' => '消息称iOS 7将继续攻占车载系统 增加地图和Siri存在性',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2013/0501/20130501015933332.jpg',
    'keywords' => '消息称 继续 攻占',
    'description' => '    昨天，有知情人士爆料称iOS7将拥有全新的界面设计，新界面看起来非常扁平。今天，最新的消息显示苹果想要在下一代移动操作系统中继...',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=114',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1367344714',
    'updatetime' => '1367765986',
    'hitsid' => 'c-1-114',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '6',
    'typeid' => '0',
    'title' => '科技界十位大佬说过的最愚蠢的话',
    'style' => '',
    'thumb' => '/2013/0418/20130418021032792.jpg',
    'keywords' => '科技界 十位 说过',
    'description' => '科技博客Business Insider日前总结了科技行业十位最聪明的人曾经做出的最离谱预测.',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1366265240',
    'updatetime' => '1367735062',
    'hitsid' => 'c-1-2',
    'views' => '10',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '6',
    'typeid' => '0',
    'title' => '强攻360腹地：百度杀毒正式亮相',
    'style' => '',
    'thumb' => '/2013/0418/20130418030125695.jpg',
    'keywords' => '强攻 腹地 百度',
    'description' => '早在2月份百度面向泰国推出百度杀毒软件2013的时候，我们就预言，百度很快就会面向国内市场推出杀毒软件，这一天来的很快。今天，百度杀毒（Baidu Antivirus）正式亮相，官网提供了百度杀毒.',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1366268368',
    'updatetime' => '1366432854',
    'hitsid' => 'c-1-6',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  16 => 
  array (
    'id' => '16',
    'catid' => '6',
    'typeid' => '0',
    'title' => '强攻360腹地：百度杀毒正式亮相',
    'style' => '',
    'thumb' => '/2013/0418/20130418030133338.jpg',
    'keywords' => '强攻 腹地 百度',
    'description' => '早在2月份百度面向泰国推出百度杀毒软件2013的时候，我们就预言，百度很快就会面向国内市场推出杀毒软件，这一天来的很快。今天，百度杀毒（Baidu Antivirus）正式亮相，官网提供了百度杀毒.',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=6&id=16',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'phpcms',
    'inputtime' => '1366268368',
    'updatetime' => '1366268926',
    'hitsid' => 'c-1-16',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>